# Windows winget IDs
win_packages=(
    "wez.wezterm"
    "Microsoft.VisualStudioCode"
    "Git.Git"
    "GitHub.cli"
    "BurntSushi.ripgrep.MSVC"
    "DEVCOM.JetBrainsMonoNerdFont"
    "Starship.Starship"
)

# Mac brew formulae/casks
mac_packages=(
    "wezterm"
    "visual-studio-code"
    "git"
    "gh"
    "ripgrep"
    "font-jetbrains-mono-nerd-font"
    "herdr"
    "starship"
)

# Ubuntu apt packages
ubuntu_packages=(
    "zsh"
    "wezterm"
    "code"
    "git"
    "ripgrep"
    "gh"
)
