DOT_DIR="$(cd $(dirname ${BASH_SOURCE:-$0})/../..; pwd)"
symlink_list=(
# zsh 設定
"${DOT_DIR}/zsh/.zshrc|${HOME}/.zshrc" \
"${DOT_DIR}/zsh/.zsh.d|${HOME}/.zsh.d" \
# wezterm 設定
"${DOT_DIR}/wezterm/.wezterm.lua|${HOME}/.wezterm.lua" \
"${DOT_DIR}/wezterm/.wezterm|${HOME}/.wezterm" \
# vscode 設定
"${DOT_DIR}/vscode/settings.json|${HOME}/.config/Code/User/settings.json" \
"${DOT_DIR}/vscode/keybindings.json|${HOME}/.config/Code/User/keybindings.json" \
"${DOT_DIR}/vscode/snippets|${HOME}/.config/Code/User/snippets" \
# git 設定
"${DOT_DIR}/git/.gitconfig|${HOME}/.gitconfig" \
# nvim 設定
"${DOT_DIR}/nvim|${HOME}/.config/nvim" \
# 追加 設定
)
