zsh_plugins=(
    "https://github.com/zsh-users/zsh-autosuggestions ${HOME}/.zsh/zsh-autosuggestions" \
    "https://github.com/zsh-users/zsh-syntax-highlighting.git ${HOME}/.zsh/zsh-syntax-highlighting" \
    "https://github.com/Aloxaf/fzf-tab ${HOME}/.zsh/fzf-tab" \
)
