name: Normalize Line Endings (CRLF to LF)

on:
  push:

permissions:
  contents: write

jobs:
  convert-crlf-to-lf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Convert CRLF to LF

        run: find . -type f -not -path "*/\.git/*" -exec dos2unix --quiet {} +

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: force convert CRLF to LF"
          branch: ${{ github.head_ref || github.ref_name }}
